// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAoApcvU1qGHFah4FzurSlPjwzd0o7WNU',
    appId: '1:837120378640:web:7c07bee12e104b1fd74795',
    messagingSenderId: '837120378640',
    projectId: 'bored-api-c6881',
    authDomain: 'bored-api-c6881.firebaseapp.com',
    storageBucket: 'bored-api-c6881.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8GlQ2prZ9PEaFDdguTgF2KKqNmZmHnGI',
    appId: '1:837120378640:android:2b63ad629279fefbd74795',
    messagingSenderId: '837120378640',
    projectId: 'bored-api-c6881',
    storageBucket: 'bored-api-c6881.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlwKY_HpU8wI1yvM_R92zDuePIMPOaUF8',
    appId: '1:837120378640:ios:195ac617796b134ad74795',
    messagingSenderId: '837120378640',
    projectId: 'bored-api-c6881',
    storageBucket: 'bored-api-c6881.appspot.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlwKY_HpU8wI1yvM_R92zDuePIMPOaUF8',
    appId: '1:837120378640:ios:2efc8dee62a3fb73d74795',
    messagingSenderId: '837120378640',
    projectId: 'bored-api-c6881',
    storageBucket: 'bored-api-c6881.appspot.com',
    iosBundleId: 'com.example.complete.RunnerTests',
  );
}
